version: '3'
services:
    db:
        image: mysql:5.7
        ports:
        - "3306:3306"
        environment:
          MYSQL_DATABASE: "messy"
          MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    messy:
        build: .
        environment:
            RELOAD: "--reload"
        ports:
        - "8000:8000"
        volumes:
        - .:/app/src/messy
        links:
        - db
        depends_on:
        - db

